services:
  development:
    image: bxt_development:latest
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
    build:
      context: .
      target: development
    ports:
      - "8080:8080"
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE

  production:
    image: anydistro/bxt:latest
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
    build:
      context: .
      target: production
    ports:
      - "80:8080"
    volumes:
      - persistence_volume:/app/persistence/
      - /etc/bxtd/box.yml:/app/box.yml
      - /etc/bxtd/config.toml:/app/config.toml
volumes:
  persistence_volume:
